name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ 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 }}
        TARGET_REPO: FlyAboveGrass/FlyAboveGrass.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: dist
        CNAME: https://flyabovegrass.github.io/